import type { Metadata } from "next";
import { Anuphan } from "next/font/google";
import "./globals.css";

const anuphanSans = Anuphan({
  variable: "--font-anuphan-sans",
  subsets: ["thai", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body
        className={`${anuphanSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
